RepasoActividadesEventos/Models/Actividades.cs
namespace RepasoActividadesEventos.Models
{
    public class Actividades
    {
        public int idActividad { get; set; }
        public string Nombre { get; set; }
        public int jugadores_min { get; set; }
    }
}

RepasoActividadesEventos/Models/Curso.cs
namespace RepasoActividadesEventos.Models
{
    public class Curso
    {
        public int IdCurso { get; set; }
        public string Nombre { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public bool Activo { get; set; }
    }
}

RepasoActividadesEventos/Models/ErrorViewModel.cs
namespace RepasoActividadesEventos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RepasoActividadesEventos/Models/EventoActividad.cs
namespace RepasoActividadesEventos.Models
{
    public class EventoActividad
    {
        public int idEventoActividad { get; set; }
        public int idEvento { get; set; }
        public int idActividad { get; set; }
    }
}

RepasoActividadesEventos/Models/Inscripciones.cs
namespace RepasoActividadesEventos.Models
{
    public class Inscripciones
    {
        public int IdInscripcion { get; set; }
        public int IdUsuario { get; set; }
        public int IdEventoActividad { get; set; }
        public bool QuiereSerCapitan { get; set; }
        public DateTime FechaInscripcion { get; set; }
        public string NombreActividad { get; set; }
    }
}

RepasoActividadesEventos/Models/ResumenUsuario.cs
namespace RepasoActividadesEventos.Models
{
    public class ResumenUsuario
    {
        public Usuarios usu { get; set; }
        public List<Inscripciones> inscripciones { get; set; }
        public string nombreCurso { get; set; }

        public ResumenUsuario()
        {
            inscripciones = new List<Inscripciones>();
        }
    }
}

RepasoActividadesEventos/Models/Usuarios.cs
namespace RepasoActividadesEventos.Models
{
    public class Usuarios
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Imagen { get; set; }
        public int IdCurso { get; set; }
    }
}

RepasoActividadesEventos/Controllers/AlumnosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RepasoActividadesEventos.Models;
using RepasoActividadesEventos.Repositories;

namespace RepasoActividadesEventos.Controllers
{
    public class AlumnosController : Controller
    {
        RepositoryAlumnos repoAl;
        RepositoryActividades repoAc;
        RepositoryInscripciones repoIn;
        RepositoryCurso repoCu;
        public AlumnosController()
        {
            this.repoAl = new RepositoryAlumnos();
            this.repoAc = new RepositoryActividades();
            this.repoIn = new RepositoryInscripciones();
            this.repoCu = new RepositoryCurso();
        }
        public ActionResult Index()
        {
            List<Usuarios> u = this.repoAl.LoadUsuarios();
            return View(u);
        }
        public ActionResult Details(int id)
        {
            Usuarios u = this.repoAl.FindUsuario(id);
            List<Inscripciones> inscripciones = this.repoIn.GetInscripcionesUsuario(id);
            List<Actividades> a = this.repoAc.GetActividades();
            Curso c = this.repoCu.GetCursos(u.IdCurso);

            foreach (var ins in inscripciones)
            {
                ins.NombreActividad = a.FirstOrDefault(x => x.idActividad == ins.IdEventoActividad).Nombre;
            }

            ResumenUsuario res=new ResumenUsuario()
            {
                usu = u,
                inscripciones = inscripciones,
                nombreCurso = c.Nombre
            };

            return View(res);
        }
    }
}

RepasoActividadesEventos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RepasoActividadesEventos.Models;
using System.Diagnostics;

namespace RepasoActividadesEventos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RepasoActividadesEventos/Views/Alumnos/Details.cshtml
@model ResumenUsuario
<h1>Detalles del Alumno</h1>
<h2>Nombre: @Model.usu.Nombre @Model.usu.Apellidos</h2>
<h2>Email: @Model.usu.Email</h2>
<h2>Imagen: <img src="@Model.usu.Imagen" style="width: 30px; height: 30px"/></h2>
<hr>
<h1>Actividades</h1>
<table class="table-active w-75 mx-auto">
    <thead>
        <th>Nombre</th>
        <th>Fecha</th>
        <th>Capitan</th>
        <th>Curso</th>
    </thead>
    <tbody>
        @foreach(Inscripciones res in @Model.inscripciones)
        {
            <tr>
                <td>@res.NombreActividad</td>
                <td>@res.FechaInscripcion</td>
                <td>@res.QuiereSerCapitan</td>
                <td>@Model.nombreCurso</td>
            </tr>
        }
    </tbody>
</table>

RepasoActividadesEventos/Views/Alumnos/Index.cshtml
@model List<Usuarios>;

<h1>Alumnos: </h1>

<table class="table-active w-75 mx-auto">
    <thead>
        <th>Id Usuario</th>
        <th>Nombre</th>
        <th>Email</th>
    </thead>
    <tbody>
        @foreach (var alumno in Model)
        {
            <tr>
                <td>@alumno.IdUsuario</td>
                <td>@alumno.Nombre</td>
                <td>@alumno.Email</td>
                <td>
                    <a asp-action="Details" asp-route-id="@alumno.IdUsuario" class="btn btn-warning">Details</a>
                </td>
            </tr>
        }
</table>

RepasoActividadesEventos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RepasoActividadesEventos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RepasoActividadesEventos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RepasoActividadesEventos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RepasoActividadesEventos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumnos" asp-action="Index">Alumnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - RepasoActividadesEventos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>